# Generated by Django 4.2.4 on 2023-12-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Фото баннера')),
                ('mobile_image', models.ImageField(upload_to='banners_mobile/', verbose_name='Фото баннера (для мобильной версии)')),
                ('position', models.PositiveIntegerField(verbose_name='Позиция фото')),
            ],
        ),
    ]
