# Generated by Django 4.2.4 on 2023-11-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0005_alter_country_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Позиция'),
        ),
    ]
