# Generated by Django 4.2.4 on 2023-10-27 14:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='service',
            name='text_kk',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='service',
            name='text_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст'),
        ),
    ]
