# Generated by Django 4.2.4 on 2023-11-09 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_name_en_service_name_kk_service_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'verbose_name': 'Фото услуги', 'verbose_name_plural': 'Фотографии услуг'},
        ),
    ]
