# Generated by Django 4.2.4 on 2023-11-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_options_alter_serviceimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='position',
            field=models.PositiveIntegerField(verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='position',
            field=models.PositiveIntegerField(verbose_name='Позиция'),
        ),
    ]
