# Generated by Django 4.2.4 on 2023-11-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_position_alter_serviceimage_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='detail_image',
            field=models.ImageField(null=True, upload_to='services/', verbose_name='Внутренее фото'),
        ),
    ]
