# Generated by Django 4.2.4 on 2023-11-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_detail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Краткое описание'),
        ),
    ]
