# Generated by Django 4.2.4 on 2023-12-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='advantage_icons/', verbose_name='Иконка')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=150, null=True, verbose_name='Заголовок')),
                ('title_kk', models.CharField(max_length=150, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='Заголовок')),
                ('text', models.CharField(max_length=250, verbose_name='Текст')),
                ('text_ru', models.CharField(max_length=250, null=True, verbose_name='Текст')),
                ('text_kk', models.CharField(max_length=250, null=True, verbose_name='Текст')),
                ('text_en', models.CharField(max_length=250, null=True, verbose_name='Текст')),
            ],
        ),
    ]
