# Generated by Django 4.2.4 on 2023-12-12 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advantages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advantage',
            options={'verbose_name': 'Преимущество', 'verbose_name_plural': 'Преимущества'},
        ),
    ]
