# Generated by Django 4.2.4 on 2023-12-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advantages', '0002_alter_advantage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('text', models.CharField(max_length=250, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Преимущество тура',
                'verbose_name_plural': 'Преимущества тура',
            },
        ),
    ]
