# Generated by Django 4.2.4 on 2023-09-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_rename_city_tour_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='must_know',
            field=models.TextField(blank=True, null=True, verbose_name='Важно знать'),
        ),
    ]
