# Generated by Django 4.2.4 on 2023-09-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_tour_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='budget',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Бюджет (для фильтра)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Продолжительность (для фильтра)'),
        ),
    ]
