# Generated by Django 4.2.4 on 2023-09-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_tour_budget_tour_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='budget',
            field=models.PositiveIntegerField(blank=True, help_text='Для фильтра', null=True, verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Для фильтра', null=True, verbose_name='Продолжительность'),
        ),
    ]
