# Generated by Django 4.2.4 on 2023-10-27 14:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('tours', '0006_alter_tour_budget_alter_tour_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Полное описание тура'),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_kk',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Полное описание тура'),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Полное описание тура'),
        ),
        migrations.AddField(
            model_name='tour',
            name='must_know_en',
            field=models.TextField(blank=True, null=True, verbose_name='Важно знать'),
        ),
        migrations.AddField(
            model_name='tour',
            name='must_know_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Важно знать'),
        ),
        migrations.AddField(
            model_name='tour',
            name='must_know_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Важно знать'),
        ),
        migrations.AddField(
            model_name='tour',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название тура'),
        ),
        migrations.AddField(
            model_name='tour',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название тура'),
        ),
        migrations.AddField(
            model_name='tour',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название тура'),
        ),
        migrations.AddField(
            model_name='tour',
            name='route_en',
            field=models.TextField(null=True, verbose_name='Маршрут тура'),
        ),
        migrations.AddField(
            model_name='tour',
            name='route_kk',
            field=models.TextField(null=True, verbose_name='Маршрут тура'),
        ),
        migrations.AddField(
            model_name='tour',
            name='route_ru',
            field=models.TextField(null=True, verbose_name='Маршрут тура'),
        ),
        migrations.AddField(
            model_name='tour',
            name='short_description_en',
            field=models.TextField(null=True, verbose_name='Краткое описание тура'),
        ),
        migrations.AddField(
            model_name='tour',
            name='short_description_kk',
            field=models.TextField(null=True, verbose_name='Краткое описание тура'),
        ),
        migrations.AddField(
            model_name='tour',
            name='short_description_ru',
            field=models.TextField(null=True, verbose_name='Краткое описание тура'),
        ),
        migrations.AddField(
            model_name='tour',
            name='tags_en',
            field=models.ManyToManyField(null=True, to='tags.tag', verbose_name='Тэги'),
        ),
        migrations.AddField(
            model_name='tour',
            name='tags_kk',
            field=models.ManyToManyField(null=True, to='tags.tag', verbose_name='Тэги'),
        ),
        migrations.AddField(
            model_name='tour',
            name='tags_ru',
            field=models.ManyToManyField(null=True, to='tags.tag', verbose_name='Тэги'),
        ),
        migrations.AddField(
            model_name='tourformat',
            name='name_en',
            field=models.CharField(help_text='Например "Городские туры"', max_length=255, null=True, verbose_name='Название формата тура'),
        ),
        migrations.AddField(
            model_name='tourformat',
            name='name_kk',
            field=models.CharField(help_text='Например "Городские туры"', max_length=255, null=True, verbose_name='Название формата тура'),
        ),
        migrations.AddField(
            model_name='tourformat',
            name='name_ru',
            field=models.CharField(help_text='Например "Городские туры"', max_length=255, null=True, verbose_name='Название формата тура'),
        ),
        migrations.AddField(
            model_name='tourplacement',
            name='name_en',
            field=models.CharField(help_text='Например "Отели"', max_length=255, null=True, verbose_name='Тип размещения'),
        ),
        migrations.AddField(
            model_name='tourplacement',
            name='name_kk',
            field=models.CharField(help_text='Например "Отели"', max_length=255, null=True, verbose_name='Тип размещения'),
        ),
        migrations.AddField(
            model_name='tourplacement',
            name='name_ru',
            field=models.CharField(help_text='Например "Отели"', max_length=255, null=True, verbose_name='Тип размещения'),
        ),
        migrations.AddField(
            model_name='tourprice',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Информация о стоимости'),
        ),
        migrations.AddField(
            model_name='tourprice',
            name='text_kk',
            field=models.TextField(null=True, verbose_name='Информация о стоимости'),
        ),
        migrations.AddField(
            model_name='tourprice',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Информация о стоимости'),
        ),
        migrations.AddField(
            model_name='tourprogram',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание дня'),
        ),
        migrations.AddField(
            model_name='tourprogram',
            name='description_kk',
            field=models.TextField(null=True, verbose_name='Описание дня'),
        ),
        migrations.AddField(
            model_name='tourprogram',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание дня'),
        ),
        migrations.AddField(
            model_name='tourprogram',
            name='food_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Еда маршрута'),
        ),
        migrations.AddField(
            model_name='tourprogram',
            name='food_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Еда маршрута'),
        ),
        migrations.AddField(
            model_name='tourprogram',
            name='food_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Еда маршрута'),
        ),
        migrations.AddField(
            model_name='tourprogram',
            name='route_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Маршрут программы'),
        ),
        migrations.AddField(
            model_name='tourprogram',
            name='route_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Маршрут программы'),
        ),
        migrations.AddField(
            model_name='tourprogram',
            name='route_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Маршрут программы'),
        ),
        migrations.AddField(
            model_name='tourseason',
            name='name_en',
            field=models.CharField(help_text='Например "Осень"', max_length=255, null=True, verbose_name='Сезон'),
        ),
        migrations.AddField(
            model_name='tourseason',
            name='name_kk',
            field=models.CharField(help_text='Например "Осень"', max_length=255, null=True, verbose_name='Сезон'),
        ),
        migrations.AddField(
            model_name='tourseason',
            name='name_ru',
            field=models.CharField(help_text='Например "Осень"', max_length=255, null=True, verbose_name='Сезон'),
        ),
    ]
