# Generated by Django 4.2.4 on 2023-11-09 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_tour_description_en_tour_description_kk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'Тур', 'verbose_name_plural': 'Туры'},
        ),
        migrations.AlterModelOptions(
            name='tourdate',
            options={'verbose_name': 'Даты тура', 'verbose_name_plural': 'Даты туров'},
        ),
        migrations.AlterModelOptions(
            name='tourformat',
            options={'verbose_name': 'Формат', 'verbose_name_plural': 'Форматы'},
        ),
        migrations.AlterModelOptions(
            name='tourimage',
            options={'verbose_name': 'Картинка тура', 'verbose_name_plural': 'Картинки туров'},
        ),
        migrations.AlterModelOptions(
            name='tourplacement',
            options={'verbose_name': 'Тип размещения', 'verbose_name_plural': 'Типы размещении'},
        ),
        migrations.AlterModelOptions(
            name='tourprice',
            options={'verbose_name': 'Цена тура', 'verbose_name_plural': 'Цены туров'},
        ),
        migrations.AlterModelOptions(
            name='tourprogram',
            options={'verbose_name': 'Программа тура', 'verbose_name_plural': 'Программы туров'},
        ),
        migrations.AlterModelOptions(
            name='tourprogramimage',
            options={'verbose_name': 'Фото программы тура', 'verbose_name_plural': 'Фотографии программ туров'},
        ),
        migrations.AlterModelOptions(
            name='tourseason',
            options={'verbose_name': 'Сезон', 'verbose_name_plural': 'Сезоны'},
        ),
    ]
