# Generated by Django 4.2.4 on 2023-12-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_tourprogram_title_tourprogram_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='days',
            field=models.PositiveIntegerField(null=True, verbose_name='Количство дней'),
        ),
        migrations.AddField(
            model_name='tour',
            name='nights',
            field=models.PositiveIntegerField(null=True, verbose_name='Количество ночей'),
        ),
    ]
