# Generated by Django 4.2.4 on 2023-12-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advantages', '0002_alter_advantage_options'),
        ('tours', '0010_tour_days_tour_nights'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='advantages',
            field=models.ManyToManyField(to='advantages.advantage', verbose_name='Преимущества'),
        ),
        migrations.AddField(
            model_name='tourprice',
            name='discount_till_date',
            field=models.DateField(blank=True, null=True, verbose_name='Скидка до'),
        ),
    ]
