# Generated by Django 4.2.4 on 2023-12-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_accommodation_accommodationimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourformat',
            name='image',
            field=models.ImageField(null=True, upload_to='tour_formats/', verbose_name='Фото формата тура'),
        ),
    ]
