# Generated by Django 4.2.4 on 2023-12-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advantages', '0003_touradvantage'),
        ('tours', '0013_tourformat_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tags_en',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tags_kk',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tags_ru',
        ),
        migrations.AlterField(
            model_name='tour',
            name='advantages',
            field=models.ManyToManyField(to='advantages.touradvantage', verbose_name='Преимущества'),
        ),
    ]
