# Generated by Django 4.2.4 on 2023-12-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_remove_tour_tags_remove_tour_tags_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MustKnow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('text_ru', models.TextField(null=True, verbose_name='Текст')),
                ('text_kk', models.TextField(null=True, verbose_name='Текст')),
                ('text_en', models.TextField(null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Важно знать',
                'verbose_name_plural': 'Важно знать',
            },
        ),
        migrations.RemoveField(
            model_name='tour',
            name='must_know_en',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='must_know_kk',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='must_know_ru',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='must_know',
        ),
        migrations.AddField(
            model_name='tour',
            name='must_know',
            field=models.ManyToManyField(to='tours.mustknow', verbose_name='Важно знать'),
        ),
    ]
