# Generated by Django 4.2.4 on 2023-12-14 18:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0016_alter_tour_advantages'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='distance',
            field=models.PositiveIntegerField(null=True, verbose_name='Дистанция (в км)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='included_things',
            field=ckeditor.fields.RichTextField(help_text='Информация о том что включено/не включено в стоимость тура', null=True, verbose_name='Включено/Не включено'),
        ),
        migrations.AddField(
            model_name='tour',
            name='included_things_en',
            field=ckeditor.fields.RichTextField(help_text='Информация о том что включено/не включено в стоимость тура', null=True, verbose_name='Включено/Не включено'),
        ),
        migrations.AddField(
            model_name='tour',
            name='included_things_kk',
            field=ckeditor.fields.RichTextField(help_text='Информация о том что включено/не включено в стоимость тура', null=True, verbose_name='Включено/Не включено'),
        ),
        migrations.AddField(
            model_name='tour',
            name='included_things_ru',
            field=ckeditor.fields.RichTextField(help_text='Информация о том что включено/не включено в стоимость тура', null=True, verbose_name='Включено/Не включено'),
        ),
        migrations.AddField(
            model_name='tour',
            name='main_image_text',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст на главном фото'),
        ),
        migrations.AddField(
            model_name='tour',
            name='main_image_text_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст на главном фото'),
        ),
        migrations.AddField(
            model_name='tour',
            name='main_image_text_kk',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст на главном фото'),
        ),
        migrations.AddField(
            model_name='tour',
            name='main_image_text_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст на главном фото'),
        ),
    ]
