# Generated by Django 4.2.4 on 2023-12-15 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0017_tour_distance_tour_included_things_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourprogram',
            name='accommodation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_programs', to='tours.accommodation', verbose_name='Проживание'),
        ),
    ]
