# Generated by Django 4.2.4 on 2023-12-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0018_alter_tourprogram_accommodation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='direction',
        ),
    ]
