# Generated by Django 4.2.4 on 2023-09-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('experience', models.PositiveIntegerField(verbose_name='Опыт работы')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='specialists/', verbose_name='Фото специалиста')),
            ],
        ),
    ]
