# Generated by Django 4.2.4 on 2023-10-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='specialist',
            name='description_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='specialist',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='specialist',
            name='full_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Полное имя'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='full_name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Полное имя'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='full_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Полное имя'),
        ),
    ]
