# Generated by Django 4.2.4 on 2023-10-27 14:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название документа')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='Название документа')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название документа')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('text_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Текст')),
                ('text_kk', ckeditor.fields.RichTextField(null=True, verbose_name='Текст')),
                ('text_en', ckeditor.fields.RichTextField(null=True, verbose_name='Текст')),
                ('position', models.PositiveIntegerField(verbose_name='Позиция')),
            ],
        ),
    ]
