# Generated by Django 4.2.4 on 2023-12-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='text',
        ),
        migrations.RemoveField(
            model_name='document',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='document',
            name='text_kk',
        ),
        migrations.RemoveField(
            model_name='document',
            name='text_ru',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(help_text='Заполнится сам', max_length=50, null=True, verbose_name='Тип файла'),
        ),
    ]
