# Generated by Django 4.2.4 on 2023-12-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='privacy_statements/', verbose_name='Файл "Положение о конфиденциальности"')),
            ],
            options={
                'verbose_name': 'Положение о конфиденциальности',
                'verbose_name_plural': 'Положения о конфиденциальности',
            },
        ),
    ]
