# Generated by Django 4.2.4 on 2023-09-05 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=255, verbose_name='Имя автора')),
                ('author_age', models.CharField(max_length=3, verbose_name='Возраст автора')),
                ('text', models.TextField(verbose_name='Текст')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
