# Generated by Django 4.2.4 on 2023-12-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(null=True, upload_to='reviews/', verbose_name='Фото'),
        ),
    ]
