# Generated by Django 4.2.4 on 2023-12-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tag_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя тэга'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя тэга'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя тэга'),
        ),
    ]
