# Generated by Django 4.2.4 on 2023-11-07 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0007_tour_description_en_tour_description_kk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название месяца')),
                ('name_ru', models.CharField(max_length=155, null=True, verbose_name='Название месяца')),
                ('name_kk', models.CharField(max_length=155, null=True, verbose_name='Название месяца')),
                ('name_en', models.CharField(max_length=155, null=True, verbose_name='Название месяца')),
                ('month_num', models.PositiveIntegerField(verbose_name='Номер месяца')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.tourseason', verbose_name='Сезон')),
            ],
        ),
    ]
