# Generated by Django 4.2.4 on 2023-10-27 14:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст рекоммендации'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='text_kk',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст рекоммендации'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='text_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст рекоммендации'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Рекоммендация'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Рекоммендация'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Рекоммендация'),
        ),
        migrations.AddField(
            model_name='recommendationcategory',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип рекоммендации'),
        ),
        migrations.AddField(
            model_name='recommendationcategory',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип рекоммендации'),
        ),
        migrations.AddField(
            model_name='recommendationcategory',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип рекоммендации'),
        ),
    ]
