# Generated by Django 4.2.4 on 2023-11-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_alter_recommendation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание рекоммендации'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание рекоммендации'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='description_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание рекоммендации'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='description_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание рекоммендации'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='detail_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Внутренее фото'),
        ),
    ]
