# Generated by Django 4.2.4 on 2023-11-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_recommendation_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='inside_text',
            field=models.CharField(max_length=255, null=True, verbose_name='Внутренни текст'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='inside_text_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Внутренни текст'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='inside_text_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Внутренни текст'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='inside_text_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Внутренни текст'),
        ),
    ]
